# Generated by Django 5.0.6 on 2024-06-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodsapp', '0001_initial'),
        ('shopapp', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.category'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.shop'),
        ),
        migrations.AddField(
            model_name='gooddetail',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods'),
        ),
        migrations.AddField(
            model_name='gooddetail',
            name='goodsdname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goodsdetailname'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.color'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.size'),
        ),
        migrations.AddField(
            model_name='usedgoods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.category'),
        ),
        migrations.AddField(
            model_name='usedgoods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo'),
        ),
        migrations.AddField(
            model_name='usedgoodsdetail',
            name='usedgoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.usedgoods'),
        ),
    ]
