# Generated by Django 5.0.6 on 2024-06-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedgoods',
            old_name='name',
            new_name='gname',
        ),
    ]
