# Generated by Django 5.0.6 on 2024-06-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0003_rename_name_usedgoods_gname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedgoods',
            name='ifdelete',
            field=models.BooleanField(default=False),
        ),
    ]
