# Generated by Django 5.0.6 on 2024-06-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0004_usedgoods_ifdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedgoods',
            old_name='desc',
            new_name='gdesc',
        ),
        migrations.RenameField(
            model_name='usedgoods',
            old_name='ifdelete',
            new_name='isdelete',
        ),
        migrations.AddField(
            model_name='goods',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
