# Generated by Django 5.0.6 on 2024-06-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('fan_num', models.IntegerField(default=1)),
                ('rating', models.DecimalField(decimal_places=2, default=3, max_digits=3)),
                ('slogourl', models.ImageField(default='/media/shop_logo/2.png', upload_to='shop_logo/')),
            ],
        ),
    ]
