apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-example
  labels:
    app: django-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-example
  template:
    metadata:
      labels:
        app: django-example
    spec:
      containers:
      - name: netshop-token
        image: registry.cn-hongkong.aliyuncs.com/red_scarf/netshop_token:v1
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_NAME
            value: "db"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            value: "123456"
          - name: DATABASE_HOST
            value: "my-mysql"
          - name: DATABASE_PORT
            value: "3306"
      imagePullSecrets:  # 调整到 containers 同一级
        - name: mysecret