version: '3'
services:
  db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"

  web:
    build: .
    container_name: netshop-token
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/djtest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
