# Generated by Django 5.0.6 on 2024-06-08 03:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodsapp', '0001_initial'),
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaid', models.IntegerField(help_text='区域编号', primary_key=True, serialize=False)),
                ('areaname', models.CharField(help_text='区域名称', max_length=50)),
                ('parentid', models.IntegerField(help_text='父级编号')),
                ('arealevel', models.IntegerField(help_text='区域等级(1省/2市/3区县)')),
                ('status', models.IntegerField(help_text='状态（1可用/0不可用）')),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=1000)),
                ('uidentity', models.CharField(default='student', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FollowShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=30)),
                ('aphone', models.CharField(max_length=11)),
                ('addr', models.CharField(max_length=100)),
                ('isdefault', models.BooleanField(default=False)),
                ('userinfo', models.ForeignKey(help_text='用户信息', on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo')),
            ],
            options={
                'unique_together': {('user', 'goods')},
            },
        ),
    ]
